# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_layer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
