# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20170820_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.MLModel')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.AddField(
            model_name='layerproperty',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
