# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_auto_20170820_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
                ('image', models.ImageField(upload_to='examples/')),
                ('description', models.TextField()),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.MLModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='examples',
            name='ml_model',
        ),
        migrations.DeleteModel(
            name='Examples',
        ),
    ]
