# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:15
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_mlmodel_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerproperty',
            name='layer',
        ),
        migrations.AddField(
            model_name='layer',
            name='properties',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LayerProperty',
        ),
    ]
