# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 01:24
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_auto_20170822_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='weights',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
    ]
