# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_auto_20170826_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
