# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 20:18
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import hub.models
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0023_auto_20170905_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=1)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
                ('framework', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='weights',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AddField(
            model_name='preprocessor',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.MLModel'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.MLModel'),
        ),
        migrations.AddField(
            model_name='classes',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.MLModel'),
        ),
    ]
