# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0025_dimension_dtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessor',
            name='framework',
        ),
    ]
