# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_auto_20171108_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='demos/')),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.MLModel')),
            ],
        ),
    ]
