# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 03:55
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0028_demoresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='output_classes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='weights',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
    ]
