# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 22:55
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0029_auto_20171123_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='sample',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/var/www/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='weights',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/var/www/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
    ]
