# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 23:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0030_auto_20180101_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='architecture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='about',
            field=models.TextField(default=' ', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/lyterai/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='weights',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/models/', location='/home/jasonchin/projects/lyterai/lyterai/app/storage/models'), upload_to=hub.models.get_model_upload_to),
        ),
    ]
