# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('input_shape', models.CharField(max_length=50)),
                ('output_shape', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LayerProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('value_type', models.CharField(max_length=20)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=200)),
                ('accuracy', models.FloatField()),
                ('image', models.ImageField(upload_to='models/')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='ml_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.MLModel'),
        ),
    ]
