# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20170817_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
