# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_mlmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
