# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20170820_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
