# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_auto_20170822_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='path',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='weights',
            field=models.FileField(blank=True, null=True, upload_to=hub.models.get_model_upload_to),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='description',
            field=models.TextField(max_length=140),
        ),
    ]
